from setuptools import setup, find_packages


setup(
    name="mozart",
    version="2.3.2",
    long_description="HySDS job orchestration/worker web interface",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    python_requires=">=3.12",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    install_requires=[
        "Flask>=2.3.0,<3.0.0",
        "flask-restx>=1.3.0",
        "Flask-SQLAlchemy>=3.1.0",
        "Flask-WTF>=1.2.0",
        "Flask-DebugToolbar>=0.15.0",
        "Flask-Login>=0.6.0",
        "Flask-CORS>=4.0.0",
        "gunicorn>=21.0.0",
        "gevent>=23.0.0",
        "eventlet>=0.35.0",
        "requests>=2.31.0",
        "simpleldap>=0.8",
        "simplekml>=1.3.0",
        "tornado>=6.4.0",
        "pika>=1.3.0",
        "pymongo>=4.6.0",
        "boto3>=1.34.0",
        "python-dateutil>=2.8.0",
        'elasticsearch>=7.0.0,<7.14.0',
        "python-jenkins>=1.8.0",
        "pytz>=2023.3",
        "numpy>=1.26.0",
        "werkzeug>=3.0.0",
        "cryptography>=41.0.0",
    ],
)
